### PR TITLE
Adds some math

### PR DESCRIPTION
**Pull request by ruddfawcett**
Adds Clamped.swift to start.

### CODE REVIEW

**Comment by ruddfawcett** [comment]
Should I add some unit testing?

**Comment by surayashivji** [comment]
yeah I think that's best practice

**Comment by ruddfawcett** [comment]
@surayashivji are you going to open a separate PR? Or should I make a Jira ticket to track?

**Review by danielamitay — APPROVED** [review]
LGTM, thank you for the contribution but please make sure to get Privacy, Legal, and Security approval before merging! Thanks!

**Pull request merged**
